#ifndef _PARAMS_H_
#define _PARAMS_H_

#define CQ_HEADER_LEN 4
#define CQ_MESSAGE_LEN 100
#define CQ_DATA_MAX_LEN (CQ_HEADER_LEN + CQ_MESSAGE_LEN)
#define CQ_MAX_DATA_AMOUNT 10
#define MESSAGE_PDU_SIZE CQ_DATA_MAX_LEN
#define HEADER_PDU_SIZE 8
#define PDU_SIZE (MESSAGE_PDU_SIZE + HEADER_PDU_SIZE)

#endif